// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// findInterval_equi
IntegerVector findInterval_equi(NumericVector x, double low, double high, int nbin, StringVector labels, bool right, bool explicit_na, bool codes_only);
RcppExport SEXP _effectplots_findInterval_equi(SEXP xSEXP, SEXP lowSEXP, SEXP highSEXP, SEXP nbinSEXP, SEXP labelsSEXP, SEXP rightSEXP, SEXP explicit_naSEXP, SEXP codes_onlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type low(lowSEXP);
    Rcpp::traits::input_parameter< double >::type high(highSEXP);
    Rcpp::traits::input_parameter< int >::type nbin(nbinSEXP);
    Rcpp::traits::input_parameter< StringVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< bool >::type right(rightSEXP);
    Rcpp::traits::input_parameter< bool >::type explicit_na(explicit_naSEXP);
    Rcpp::traits::input_parameter< bool >::type codes_only(codes_onlySEXP);
    rcpp_result_gen = Rcpp::wrap(findInterval_equi(x, low, high, nbin, labels, right, explicit_na, codes_only));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_effectplots_findInterval_equi", (DL_FUNC) &_effectplots_findInterval_equi, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_effectplots(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
