# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' findInterval() for equi-length intervals
#'
#' @noRd
#' @keywords internal
#' @param x Numeric vector to be binned.
#' @param low Lowest value.
#' @param low Highest value.
#' @param nbin Number of bins (= length(breaks) - 1L).
#' @param right Right-closed intervals? Default is `true`.
#' @return A factor representing a binned version of `x`. In line with collapse,
#'   missing values are encoded internally by an explicit level "NA" to allow for
#'   zero-copy grouped stats.
findInterval_equi <- function(x, low, high, nbin, right = TRUE) {
    .Call(`_effectplots_findInterval_equi`, x, low, high, nbin, right)
}

