# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Clamps/clips Vector
#'
#' Much faster than `pmax(pmin, x, high), low)`.
#'
#' @noRd
#' @keywords internal
#' @param x Numeric vector to be clamped/clipped.
#' @param low Lowest value.
#' @param low Highest value.
#' @return Clamped version of x.
clamp2 <- function(x, low, high) {
    .Call(`_effectplots_clamp2`, x, low, high)
}

#' findInterval() for equi-length intervals
#'
#' Results agree with `findInterval(..., rightmost.closed = TRUE, all.inside = TRUE)`.
#'
#' @noRd
#' @keywords internal
#' @param x Numeric vector to be binned.
#' @param low Lowest value.
#' @param low Highest value.
#' @param nbin Number of bins (= length(breaks) - 1L).
#' @param right Right-closed intervals? Default is `true`.
#' @return Binned version of `x` (integer encoded).
findInterval_equi <- function(x, low, high, nbin, right = TRUE) {
    .Call(`_effectplots_findInterval_equi`, x, low, high, nbin, right)
}

